name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Mets la version utilisée dans ton projet

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installe les dépendances si fichier requirements.txt présent

      - name: Run tests
        run: pytest  # Exécute les tests unitaires
